#ifndef __OFED_BUILD__
#include_next <linux/autoconf.h>
#else
#undef CONFIG_MEMTRACK
#undef CONFIG_DEBUG_INFO
#undef CONFIG_INFINIBAND
#undef CONFIG_INFINIBAND_IPOIB
#undef CONFIG_INFINIBAND_IPOIB_CM
#undef CONFIG_INFINIBAND_SDP
#undef CONFIG_INFINIBAND_SRP
#undef CONFIG_INFINIBAND_SRPT

#undef CONFIG_INFINIBAND_USER_MAD
#undef CONFIG_INFINIBAND_USER_ACCESS
#undef CONFIG_INFINIBAND_ADDR_TRANS
#undef CONFIG_INFINIBAND_USER_MEM
#undef CONFIG_INFINIBAND_MTHCA

#undef CONFIG_MLX4_CORE
#undef CONFIG_MLX4_DEBUG
#undef CONFIG_MLX4_EN
#undef CONFIG_MLX4_INFINIBAND

#undef CONFIG_INFINIBAND_RXE

#undef CONFIG_INFINIBAND_IPOIB_DEBUG
#undef CONFIG_INFINIBAND_ISER
#undef CONFIG_INFINIBAND_EHCA
#undef CONFIG_INFINIBAND_EHCA_SCALING
#undef CONFIG_RDS
#undef CONFIG_RDS_RDMA
#undef CONFIG_RDS_TCP
#undef CONFIG_RDS_DEBUG
#undef CONFIG_INFINIBAND_MADEYE
#undef CONFIG_INFINIBAND_QLGC_VNIC
#undef CONFIG_INFINIBAND_QLGC_VNIC_STATS
#undef CONFIG_INFINIBAND_CXGB3
#undef CONFIG_INFINIBAND_CXGB3_DEBUG
#undef CONFIG_CHELSIO_T3
#undef CONFIG_INFINIBAND_NES
#undef CONFIG_INFINIBAND_NES_DEBUG

#undef CONFIG_SUNRPC_XPRT_RDMA
#undef CONFIG_SUNRPC
#undef CONFIG_SUNRPC_GSS
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_NFS_FS
#undef CONFIG_NFS_V3
#undef CONFIG_NFS_V3_ACL
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_ACL_SUPPORT
#undef CONFIG_NFS_DIRECTIO
#undef CONFIG_EXPORTFS
#undef CONFIG_LOCKD
#undef CONFIG_LOCKD_V4
#undef CONFIG_NFSD
#undef CONFIG_NFSD_V2_ACL
#undef CONFIG_NFSD_V3
#undef CONFIG_NFSD_V3_ACL
#undef CONFIG_NFSD_V4
#undef CONFIG_NFSD_RDMA

#undef CONFIG_INFINIBAND_IPOIB_DEBUG_DATA
#undef CONFIG_INFINIBAND_SDP_SEND_ZCOPY
#undef CONFIG_INFINIBAND_SDP_RECV_ZCOPY
#undef CONFIG_INFINIBAND_SDP_DEBUG
#undef CONFIG_INFINIBAND_SDP_DEBUG_DATA
#undef CONFIG_INFINIBAND_IPATH
#undef CONFIG_INFINIBAND_QIB
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#undef CONFIG_INFINIBAND_AMSO1100
#endif

/* CONFIG_INFINIBAND is not set */
/* CONFIG_INFINIBAND_IPOIB is not set */
/* CONFIG_INFINIBAND_IPOIB_CM is not set */
/* CONFIG_INFINIBAND_SDP is not set */
/* CONFIG_INFINIBAND_SRP is not set */
/* CONFIG_INFINIBAND_SRPT is not set */

/* CONFIG_INFINIBAND_USER_MAD is not set */
/* CONFIG_INFINIBAND_USER_ACCESS is not set */
/* CONFIG_INFINIBAND_ADDR_TRANS is not set */
/* CONFIG_INFINIBAND_USER_MEM is not set */
/* CONFIG_INFINIBAND_MTHCA is not set */
/* CONFIG_INFINIBAND_QLGC_VNIC is not set */
/* CONFIG_INFINIBAND_CXGB3 is not set */
/* CONFIG_CHELSIO_T3 is not set */
/* CONFIG_INFINIBAND_NES is not set */

/* CONFIG_SUNRPC_XPRT_RDMA is not set */
/* CONFIG_SUNRPC is not set */
/* CONFIG_SUNRPC_GSS is not set */
/* CONFIG_RPCSEC_GSS_KRB5 is not set */
/* CONFIG_RPCSEC_GSS_SPKM3 is not set */
/* CONFIG_NFS_FS is not set */
/* CONFIG_NFS_V3 is not set */
/* CONFIG_NFS_V3_ACL is not set */
/* CONFIG_NFS_V4 is not set */
/* CONFIG_NFS_ACL_SUPPORT is not set */
/* CONFIG_NFS_DIRECTIO is not set */
/* CONFIG_EXPORTFS is not set */
/* CONFIG_LOCKD is not set */
/* CONFIG_LOCKD_V4 is not set */
/* CONFIG_NFSD is not set */
/* CONFIG_NFSD_V2_ACL is not set */
/* CONFIG_NFSD_V3 is not set */
/* CONFIG_NFSD_V3_ACL is not set */
/* CONFIG_NFSD_V4 is not set */
/* CONFIG_NFSD_RDMA is not set */

/* CONFIG_INFINIBAND_IPOIB_DEBUG is not set */
/* CONFIG_INFINIBAND_ISER is not set */
/* CONFIG_SCSI_ISCSI_ATTRS is not set */
/* CONFIG_ISCSI_TCP is not set */
/* CONFIG_INFINIBAND_EHCA is not set */
/* CONFIG_RDS is not set */
/* CONFIG_RDS_RDMA is not set */
/* CONFIG_RDS_TCP is not set */
/* CONFIG_RDS_DEBUG is not set */
/* CONFIG_INFINIBAND_QLGC_VNIC_STATS is not set */
/* CONFIG_INFINIBAND_CXGB3_DEBUG is not set */
/* CONFIG_INFINIBAND_NES_DEBUG is not set */

/* CONFIG_MLX4_CORE is not set */
/* CONFIG_MLX4_EN is not set */
/* CONFIG_MLX4_INFINIBAND is not set */

/* CONFIG_MLX4_DEBUG is not set */

/* CONFIG_INFINIBAND_RXE is not set */

/* CONFIG_INFINIBAND_IPOIB_DEBUG_DATA is not set */
/* CONFIG_INFINIBAND_SDP_SEND_ZCOPY is not set */
/* CONFIG_INFINIBAND_SDP_RECV_ZCOPY is not set */
/* CONFIG_INFINIBAND_SDP_DEBUG is not set */
/* CONFIG_INFINIBAND_SDP_DEBUG_DATA is not set */
/* CONFIG_INFINIBAND_IPATH is not set */
/* CONFIG_INFINIBAND_QIB is not set */
/* CONFIG_INFINIBAND_MTHCA_DEBUG is not set */
/* CONFIG_INFINIBAND_MADEYE is not set */
/* CONFIG_INFINIBAND_AMSO1100 is not set */

#ifndef __OFED_BUILD__
#include_next <linux/autoconf.h>
#else
#undef CONFIG_MEMTRACK
#undef CONFIG_DEBUG_INFO
#undef CONFIG_INFINIBAND
#undef CONFIG_INFINIBAND_IPOIB
#undef CONFIG_INFINIBAND_IPOIB_CM
#undef CONFIG_INFINIBAND_SDP
#undef CONFIG_INFINIBAND_SRP
#undef CONFIG_INFINIBAND_SRPT

#undef CONFIG_INFINIBAND_USER_MAD
#undef CONFIG_INFINIBAND_USER_ACCESS
#undef CONFIG_INFINIBAND_ADDR_TRANS
#undef CONFIG_INFINIBAND_USER_MEM
#undef CONFIG_INFINIBAND_MTHCA

#undef CONFIG_MLX4_CORE
#undef CONFIG_MLX4_DEBUG
#undef CONFIG_MLX4_EN
#undef CONFIG_MLX4_INFINIBAND

#undef CONFIG_INFINIBAND_RXE

#undef CONFIG_INFINIBAND_IPOIB_DEBUG
#undef CONFIG_INFINIBAND_ISER
#undef CONFIG_INFINIBAND_EHCA
#undef CONFIG_INFINIBAND_EHCA_SCALING
#undef CONFIG_RDS
#undef CONFIG_RDS_RDMA
#undef CONFIG_RDS_TCP
#undef CONFIG_RDS_DEBUG
#undef CONFIG_INFINIBAND_MADEYE
#undef CONFIG_INFINIBAND_QLGC_VNIC
#undef CONFIG_INFINIBAND_QLGC_VNIC_STATS
#undef CONFIG_INFINIBAND_CXGB3
#undef CONFIG_INFINIBAND_CXGB3_DEBUG
#undef CONFIG_CHELSIO_T3
#undef CONFIG_INFINIBAND_NES
#undef CONFIG_INFINIBAND_NES_DEBUG

#undef CONFIG_SUNRPC_XPRT_RDMA
#undef CONFIG_SUNRPC
#undef CONFIG_SUNRPC_GSS
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_NFS_FS
#undef CONFIG_NFS_V3
#undef CONFIG_NFS_V3_ACL
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_ACL_SUPPORT
#undef CONFIG_NFS_DIRECTIO
#undef CONFIG_EXPORTFS
#undef CONFIG_LOCKD
#undef CONFIG_LOCKD_V4
#undef CONFIG_NFSD
#undef CONFIG_NFSD_V2_ACL
#undef CONFIG_NFSD_V3
#undef CONFIG_NFSD_V3_ACL
#undef CONFIG_NFSD_V4
#undef CONFIG_NFSD_RDMA

#undef CONFIG_INFINIBAND_IPOIB_DEBUG_DATA
#undef CONFIG_INFINIBAND_SDP_SEND_ZCOPY
#undef CONFIG_INFINIBAND_SDP_RECV_ZCOPY
#undef CONFIG_INFINIBAND_SDP_DEBUG
#undef CONFIG_INFINIBAND_SDP_DEBUG_DATA
#undef CONFIG_INFINIBAND_IPATH
#undef CONFIG_INFINIBAND_QIB
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#undef CONFIG_INFINIBAND_AMSO1100
#endif

#undef CONFIG_INFINIBAND
#define CONFIG_INFINIBAND 1
/* CONFIG_INFINIBAND_IPOIB is not set */
/* CONFIG_INFINIBAND_IPOIB_CM is not set */
/* CONFIG_INFINIBAND_SDP is not set */
/* CONFIG_INFINIBAND_SRP is not set */
/* CONFIG_INFINIBAND_SRPT is not set */

/* CONFIG_INFINIBAND_USER_MAD is not set */
/* CONFIG_INFINIBAND_USER_ACCESS is not set */
/* CONFIG_INFINIBAND_ADDR_TRANS is not set */
/* CONFIG_INFINIBAND_USER_MEM is not set */
/* CONFIG_INFINIBAND_MTHCA is not set */
/* CONFIG_INFINIBAND_QLGC_VNIC is not set */
/* CONFIG_INFINIBAND_CXGB3 is not set */
/* CONFIG_CHELSIO_T3 is not set */
/* CONFIG_INFINIBAND_NES is not set */

/* CONFIG_SUNRPC_XPRT_RDMA is not set */
/* CONFIG_SUNRPC is not set */
/* CONFIG_SUNRPC_GSS is not set */
/* CONFIG_RPCSEC_GSS_KRB5 is not set */
/* CONFIG_RPCSEC_GSS_SPKM3 is not set */
/* CONFIG_NFS_FS is not set */
/* CONFIG_NFS_V3 is not set */
/* CONFIG_NFS_V3_ACL is not set */
/* CONFIG_NFS_V4 is not set */
/* CONFIG_NFS_ACL_SUPPORT is not set */
/* CONFIG_NFS_DIRECTIO is not set */
/* CONFIG_EXPORTFS is not set */
/* CONFIG_LOCKD is not set */
/* CONFIG_LOCKD_V4 is not set */
/* CONFIG_NFSD is not set */
/* CONFIG_NFSD_V2_ACL is not set */
/* CONFIG_NFSD_V3 is not set */
/* CONFIG_NFSD_V3_ACL is not set */
/* CONFIG_NFSD_V4 is not set */
/* CONFIG_NFSD_RDMA is not set */

/* CONFIG_INFINIBAND_IPOIB_DEBUG is not set */
/* CONFIG_INFINIBAND_ISER is not set */
/* CONFIG_SCSI_ISCSI_ATTRS is not set */
/* CONFIG_ISCSI_TCP is not set */
/* CONFIG_INFINIBAND_EHCA is not set */
/* CONFIG_RDS is not set */
/* CONFIG_RDS_RDMA is not set */
/* CONFIG_RDS_TCP is not set */
/* CONFIG_RDS_DEBUG is not set */
/* CONFIG_INFINIBAND_QLGC_VNIC_STATS is not set */
/* CONFIG_INFINIBAND_CXGB3_DEBUG is not set */
/* CONFIG_INFINIBAND_NES_DEBUG is not set */

/* CONFIG_MLX4_CORE is not set */
/* CONFIG_MLX4_EN is not set */
/* CONFIG_MLX4_INFINIBAND is not set */

/* CONFIG_MLX4_DEBUG is not set */

#undef CONFIG_INFINIBAND_RXE
#define CONFIG_INFINIBAND_RXE 1

/* CONFIG_INFINIBAND_IPOIB_DEBUG_DATA is not set */
/* CONFIG_INFINIBAND_SDP_SEND_ZCOPY is not set */
/* CONFIG_INFINIBAND_SDP_RECV_ZCOPY is not set */
/* CONFIG_INFINIBAND_SDP_DEBUG is not set */
/* CONFIG_INFINIBAND_SDP_DEBUG_DATA is not set */
/* CONFIG_INFINIBAND_IPATH is not set */
/* CONFIG_INFINIBAND_QIB is not set */
/* CONFIG_INFINIBAND_MTHCA_DEBUG is not set */
/* CONFIG_INFINIBAND_MADEYE is not set */
/* CONFIG_INFINIBAND_AMSO1100 is not set */

